### ISSUE TITLE
V3 inconsistency

### ISSUE THREAD

**Issue by featalion** [iron-io/iron_mq_java#75]
* [`Queue.touchMessage(String id)`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L182) will produce error on each call, because v3 supports touch only on reserved messages.
* None of [`Queue.touchMessage(...)`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L194-L216) supports `timeout` parameter.
* [`Queue.releaseMessage(String id, int delay)`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L475) will produce error on each call. v3 does not support release of non-reserved messages.
* [`Queue.updateSubscribers()`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L573-L576) uses common PATCH queue endpoint. But IronMQ v3 has more targeted endpoint to do that, see [`Queue.addSubscribers()`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L561-L565) method. The endpoint adds or update subscribers on a queue.
* [`Queue.deletePushMessageForSubscriber()`](https://github.com/iron-io/iron_mq_java/blob/v3/src/main/java/io/iron/ironmq/Queue.java#L685-L688) has wrong URL and body formats. Endpoint is `/#{QueueName}/messages/#{MessageId}`. JSON body must contain `reservation_id` and `subscriber_name` fields.

**Comment by featalion** [comment]
Any updates on it?

**Comment by ysadka** [comment]
Hey @pyeremenko any thoughts on the above?

**Comment by pyeremenko** [comment]
@ysadka I have this in my plans (was busy with another tasks)

**Comment by pyeremenko** [comment]
Started. Work in progress

**Comment by featalion** [comment]
Thanks!

**Comment by pyeremenko** [comment]
https://github.com/iron-io/iron_mq_java/pull/77

**Comment by featalion** [comment]
Resolved by #77
