### ISSUE TITLE
NullPointerException in io.iron.ironmq.Client.singleRequest

### ISSUE THREAD

**Issue by gracklemann** [iron-io/iron_mq_java#79]
I am trying to push a test message up to an ironmq queue from some Java code. 
I can see all our queues, I can create queue, I can dequeue a message. 
However when attempting to push a message I am getting a nullpointer exception:

Exception in thread "main" java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at io.iron.ironmq.Client.singleRequest(Client.java:218)
	at io.iron.ironmq.Client.request(Client.java:164)
	at io.iron.ironmq.Client.post(Client.java:145)
	at io.iron.ironmq.Queue.push(Queue.java:367)
	at io.iron.ironmq.Queue.push(Queue.java:329)
	at io.iron.ironmq.Queue.push(Queue.java:302)
	at testing.test.testIronMq(test.java:36)
	at testing.test.main(test.java:15)
	
My code: 	
`Client ironClient = new Client();`
`Queue queue = ironClient.queue("my-test-queue");`
`queue.push("Hello, IronMQ!");`

Code for io.iron.ironmq.Client.singleRequest(..):

    private Reader singleRequest(String method, URL url, String body) throws IOException {
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        if (method.equals("DELETE") || method.equals("PATCH")) {
            conn.setRequestMethod("POST");
            conn.setRequestProperty("X-HTTP-Method-Override", method);
        } else {
            conn.setRequestMethod(method);
        }
        conn.setRequestProperty("Authorization", "OAuth " + token);
        conn.setRequestProperty("User-Agent", "IronMQ Java Client");

        if (body != null) {
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setDoOutput(true);
        }

        conn.connect();

        if (body != null) {
            OutputStreamWriter out = new OutputStreamWriter(conn.getOutputStream(), "UTF-8");
            out.write(body);
            out.close();
        }

        int status = conn.getResponseCode();
        if (status != 200) {
            String msg;
            if (conn.getContentLength() > 0 && conn.getContentType().equals("application/json")) {
                InputStreamReader reader = null;
                try {
                    reader = new InputStreamReader(conn.getErrorStream());
                    Gson gson = new Gson();
                    Error error = gson.fromJson(reader, Error.class);
                    msg = error.msg;
                } catch (JsonSyntaxException e) {
                    msg = "IronMQ's response contained invalid JSON";
                } finally {
                    if (reader != null)
                        reader.close();
                }
            } else {
                msg = "Empty or non-JSON response";
            }
            throw new HTTPException(status, msg);
        }

        return new InputStreamReader(conn.getInputStream());
    }

From the stack trace: io.iron.ironmq.Client.singleRequest(Client.java:218)
Contains this line: reader = new InputStreamReader(conn.getErrorStream());
conn.getErrorStream() is returning null, thus the NullPointerException. 
I put a breakpoint in and the response code is 201 on the 'conn'. 
From the JavaDoc on HttpUrlConnection conn.getErrorStream() only returns a non-null 
when the connection fails, but a 201 status does not indicate an error. 
So is this a bug? I tested it against ironmq v 3.0.0 and 3.0.1. 

I have to think I must be doing something incorrectly, or everyone would be running across this. Any ideas? 
Thx

**Comment by pax95** [comment]
This has been fixed with https://github.com/iron-io/iron_mq_java/commit/52192170a0e4ab85a65cbfd5fd68ce92c5b1136e

You should try the just released  3.0.2 version

**Comment by gracklemann** [comment]
Just tested and working now.. I appreciate the quick response.
