### ISSUE TITLE
missing signature match on queue.push between 0.0.19 and 3.0.x

### ISSUE THREAD

**Issue by MikeCaspar** [iron-io/iron_mq_java#85]
queue.push ( str,  timeout, delay, expires)   does not have a match any more after switch from 0.0.19 to 3.0.x

After careful review it appears the timeout parameter has been removed from method.

Thanks.

**Comment by MikeCaspar** [comment]
Please note, this is client.queue (just in case it's not clear).

**Comment by edsrzf** [comment]
Yes, this is intentional. IronMQ v3 no longer supports per-message timeouts. You can either set a queue-level timeout that applies to all messages on the queue, or you can specify a timeout when you reserve a message.

**Comment by MikeCaspar** [comment]
Hi there,

I just looked at the actual code in version 3.

It looks like I may be incorrect.. It appears that what is missing is the expire, not the timeout.

```
 public String push(String msg, long timeout, long delay) throws IOException {
        return push(msg, timeout, delay, 0);
    }

```

**Comment by MikeCaspar** [comment]
The code is opposite to what was just said  in the message above.

Now, I'm really confused. the code says time-outs are supported but the expiry has disappeared. 

For now, I'll believe what's in the code.

I'll stay with 0.0.19 until I see 3.0.3 (again in code).

Thanks

**Comment by edsrzf** [comment]
I see three `push` methods in iron_mq_java v3:

* `push(String msg)`
* `push(String msg, long delay)`
* `push(String msg, long delay, long expiresIn)`

The last `push` method that still takes an expiration is probably an oversight and the expiration will be ignored by the server. It should be deprecated.

To (attempt to) be 100% clear:
* IronMQ v3 does not support persistent per-message timeouts, but you can specify a one-time timeout when you reserve a message
* IronMQ v3 does not support per-message expirations
* Both these can be set at the queue level

**Comment by MikeCaspar** [comment]
Hi there.

I must be missing something here. I understand what you're saying and understand it.. No probs.. thanks for the explanation.. 

However, this is the current Code showing on github at this address...

https://github.com/iron-io/iron_mq_java/blob/master/src/main/java/io/iron/ironmq/Queue.java

Could it be that because they are all long's, it's not showing as an error (still compiles and maybe it works as you expect by fluke ?).

This is the code from v3..  I'll adjust as needed.. just doesn't match this code currently in Master.

I'm happy to switch to the new approach but the code doesn't seem to support it (at least so it appears).

Sorry if I'm just a bit slow today, but the code in v3.0.3 currently in master is showing these 3 as signatures, not what you describe. ?  I'll go with whatever.. I just need to do know, do I do what you say or what the code says?

Here's the code from github as it sits now.

Respectfully waiting to find out how you suggest I proceed.  ps: Your answers are great, I'm just trying to make sure I re-factor correctly.

Hey, if I'm totally wrong here, I'll be happy to acknowledge that, my apologies.. I'm just looking at the code here... (I do't seem an expiresIn in this signature at all ) ???

Here they are for your reference (taken from github on master).

```
    public String push(String msg) throws IOException {
        return push(msg, 0);
    }

    /**
     * Pushes a messages onto the queue.
     *
     * @param msg The array of the messages to push.
     * @return The IDs of new messages
     *
     * @throws io.iron.ironmq.HTTPException If the IronMQ service returns a status other than 200 OK.
     * @throws java.io.IOException If there is an error accessing the IronMQ server.
     */
    public Ids pushMessages(String[] msg) throws IOException {
        return pushMessages(msg, 0);
    }

    /**
    * Pushes a message onto the queue.
    *
    * @param msg The body of the message to push.
    * @param timeout The message's timeout in seconds.
    * @return The new message's ID
    *
    * @throws io.iron.ironmq.HTTPException If the IronMQ service returns a status other than 200 OK.
    * @throws java.io.IOException If there is an error accessing the IronMQ server.
    */
    public String push(String msg, long timeout) throws IOException {
        return push(msg, timeout, 0);
    }

    /**
     * Pushes a messages onto the queue.
     *
     * @param msg The array of the messages to push.
     * @param timeout The message's timeout in seconds.
     * @return The IDs of new messages
     *
     * @throws io.iron.ironmq.HTTPException If the IronMQ service returns a status other than 200 OK.
     * @throws java.io.IOException If there is an error accessing the IronMQ server.
     */
    public Ids pushMessages(String msg[], long timeout) throws IOException {
        return pushMessages(msg, timeout, 0);
    }

    /**
    * Pushes a message onto the queue.
    *
    * @param msg The body of the message to push.
    * @param timeout The message's timeout in seconds.
    * @param delay The message's delay in seconds.
    * @return The new message's ID
    *
    * @throws io.iron.ironmq.HTTPException If the IronMQ service returns a status other than 200 OK.
    * @throws java.io.IOException If there is an error accessing the IronMQ server.
    */
    public String push(String msg, long timeout, long delay) throws IOException {
        return push(msg, timeout, delay, 0);
    }
```

Thanks !

**Comment by edsrzf** [comment]
Hi Mike,

The code you linked is still 0.0.19. The v3 code is on the v3 branch, though that branch will soon become master. I think that's the cause of your misunderstanding.

**Comment by MikeCaspar** [comment]
I see.

Never thought that it might be in a Branch..  I guess it surprised me because it's been available in Maven for so long (already 3 versions there) for people to reference.

Phew, feeling better now.

http://mvnrepository.com/artifact/io.iron.ironmq

Thanks for the help... I'll browse through the branch.

Thanks !

Have a good one.

Mike
